name: Daily Reboot of Fairness in AI App

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7 AM UTC daily

permissions:
  contents: write #Give write access

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} #Authenticate before pushing changes

      - name: Touch timestamp file
        run: |
          date > timestamp.txt

      - name: Commit and push change
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add timestamp.txt
          git commit -m "Daily app reboot trigger"
          git push
